name: CI

on:
  push:
    tags: [ v* ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build package
      run: |
        pip install setuptools wheel twine build
        python -m build --sdist --wheel --outdir dist/ .
    - name: Publish to PyPI
      if: github.repository == 'cyllab/ccinput'
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_TOKEN }}
