name: Tests

on:
  push:
    branches: [ main ]
    tags: [ v* ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: coverage run setup.py test
    - name: Upload Coverage
      uses: codecov/codecov-action@v1.5.2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Build package
      if: ${{ github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags') }}
      run: |
        pip install setuptools wheel twine
        python -m build --sdist --wheel --outdir dist/ .
    - name: Publish to PyPI
      if: ${{ github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags') }}
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_TOKEN }}
